pipeline {
    agent any
	
    stages {
        stage('Check Java Version') {
            steps {
                bat 'java --version'
                bat 'javac --version'
            }
        }

        stage('Check Maven Version') {
            steps {
                bat 'mvn --version'
            }
        }
        
   }
}
